### PR TITLE
clickhouse_info: add roles info per user

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
clickhouse_info: add roles info per user

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Comment by aleksvagachev** [comment]
@Andersson007 Thank you for your contribution.
1) What a file .keep?
2) Will we add information about the roles? According to the official documentation, GRANT can also be performed for roles.

**Comment by Andersson007** [comment]
> @Andersson007 Thank you for your contribution.
> 
> 1. What a file .keep?
> 2. Will we add information about the roles? According to the official documentation, GRANT can also be performed for roles.

@aleksvagachev 
1. .keep would prevent the fragments directory to be not included when it's empty. it's a common practice to use .keep
2. do you mean to expand user role info more? if yes, not in this PR, but you can file an issue and implement it or leave it for other volunteers

**Review by aleksvagachev — APPROVED** [review]

**Comment by Andersson007** [comment]
@aleksvagachev thanks for reviewing and merging!

**Pull request merged**
