### PR TITLE
clickhouse_db: add comment argument

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
clickhouse_db: add comment argument

### CODE REVIEW

**Comment by Andersson007** [comment]
@aleksvagachev do you maybe know an easy way to see docs for older server version?
E.g., on https://clickhouse.com/docs/en/sql-reference/statements/create/database#comment we can see the latest version and i don't see any toggle to switch to an older one..

**Comment by aleksvagachev** [comment]
@Andersson007 Should we add this functionality while we support version 21? Can we wait for the EOL 21? In my opinion, we are now adjusting to each version, the code is becoming more confusing. We also have not implemented receiving a comment in clickhouse_info.

**Comment by Andersson007** [comment]
@aleksvagachev i think handling multiple version in code is inevitable anyway as clickhouse is under active development and new fields are regularly added / maybe removed.

**Comment by Andersson007** [comment]
ready for review

**Comment by Andersson007** [comment]
sorry, forget to`git add` changelog fragment, done, ready for review now

**Review by aleksvagachev — APPROVED** [review]

**Pull request merged**
